/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.accounts;

import com.schematic.api.core.ClientOptions;
import com.schematic.api.core.RequestOptions;
import com.schematic.api.resources.accounts.requests.CountAccountMembersRequest;
import com.schematic.api.resources.accounts.requests.CountApiKeysRequest;
import com.schematic.api.resources.accounts.requests.CountAuditLogsRequest;
import com.schematic.api.resources.accounts.requests.CreateApiKeyRequestBody;
import com.schematic.api.resources.accounts.requests.CreateEnvironmentRequestBody;
import com.schematic.api.resources.accounts.requests.ListAccountMembersRequest;
import com.schematic.api.resources.accounts.requests.ListApiKeysRequest;
import com.schematic.api.resources.accounts.requests.ListAuditLogsRequest;
import com.schematic.api.resources.accounts.requests.ListEnvironmentsRequest;
import com.schematic.api.resources.accounts.requests.UpdateApiKeyRequestBody;
import com.schematic.api.resources.accounts.requests.UpdateEnvironmentRequestBody;
import com.schematic.api.resources.accounts.types.CountAccountMembersResponse;
import com.schematic.api.resources.accounts.types.CountApiKeysResponse;
import com.schematic.api.resources.accounts.types.CountAuditLogsResponse;
import com.schematic.api.resources.accounts.types.CreateApiKeyResponse;
import com.schematic.api.resources.accounts.types.CreateEnvironmentResponse;
import com.schematic.api.resources.accounts.types.DeleteApiKeyResponse;
import com.schematic.api.resources.accounts.types.DeleteEnvironmentResponse;
import com.schematic.api.resources.accounts.types.GetAccountMemberResponse;
import com.schematic.api.resources.accounts.types.GetApiKeyResponse;
import com.schematic.api.resources.accounts.types.GetAuditLogResponse;
import com.schematic.api.resources.accounts.types.GetEnvironmentResponse;
import com.schematic.api.resources.accounts.types.GetWhoAmIResponse;
import com.schematic.api.resources.accounts.types.ListAccountMembersResponse;
import com.schematic.api.resources.accounts.types.ListApiKeysResponse;
import com.schematic.api.resources.accounts.types.ListAuditLogsResponse;
import com.schematic.api.resources.accounts.types.ListEnvironmentsResponse;
import com.schematic.api.resources.accounts.types.QuickstartResponse;
import com.schematic.api.resources.accounts.types.UpdateApiKeyResponse;
import com.schematic.api.resources.accounts.types.UpdateEnvironmentResponse;

public class AccountsClient {
    protected final ClientOptions clientOptions;

    private final RawAccountsClient rawClient;

    public AccountsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAccountsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAccountsClient withRawResponse() {
        return this.rawClient;
    }

    public ListAccountMembersResponse listAccountMembers() {
        return this.rawClient.listAccountMembers().body();
    }

    public ListAccountMembersResponse listAccountMembers(RequestOptions requestOptions) {
        return this.rawClient.listAccountMembers(requestOptions).body();
    }

    public ListAccountMembersResponse listAccountMembers(ListAccountMembersRequest request) {
        return this.rawClient.listAccountMembers(request).body();
    }

    public ListAccountMembersResponse listAccountMembers(
            ListAccountMembersRequest request, RequestOptions requestOptions) {
        return this.rawClient.listAccountMembers(request, requestOptions).body();
    }

    public GetAccountMemberResponse getAccountMember(String accountMemberId) {
        return this.rawClient.getAccountMember(accountMemberId).body();
    }

    public GetAccountMemberResponse getAccountMember(String accountMemberId, RequestOptions requestOptions) {
        return this.rawClient.getAccountMember(accountMemberId, requestOptions).body();
    }

    public CountAccountMembersResponse countAccountMembers() {
        return this.rawClient.countAccountMembers().body();
    }

    public CountAccountMembersResponse countAccountMembers(RequestOptions requestOptions) {
        return this.rawClient.countAccountMembers(requestOptions).body();
    }

    public CountAccountMembersResponse countAccountMembers(CountAccountMembersRequest request) {
        return this.rawClient.countAccountMembers(request).body();
    }

    public CountAccountMembersResponse countAccountMembers(
            CountAccountMembersRequest request, RequestOptions requestOptions) {
        return this.rawClient.countAccountMembers(request, requestOptions).body();
    }

    public ListApiKeysResponse listApiKeys(ListApiKeysRequest request) {
        return this.rawClient.listApiKeys(request).body();
    }

    public ListApiKeysResponse listApiKeys(ListApiKeysRequest request, RequestOptions requestOptions) {
        return this.rawClient.listApiKeys(request, requestOptions).body();
    }

    public CreateApiKeyResponse createApiKey(CreateApiKeyRequestBody request) {
        return this.rawClient.createApiKey(request).body();
    }

    public CreateApiKeyResponse createApiKey(CreateApiKeyRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.createApiKey(request, requestOptions).body();
    }

    public GetApiKeyResponse getApiKey(String apiKeyId) {
        return this.rawClient.getApiKey(apiKeyId).body();
    }

    public GetApiKeyResponse getApiKey(String apiKeyId, RequestOptions requestOptions) {
        return this.rawClient.getApiKey(apiKeyId, requestOptions).body();
    }

    public UpdateApiKeyResponse updateApiKey(String apiKeyId) {
        return this.rawClient.updateApiKey(apiKeyId).body();
    }

    public UpdateApiKeyResponse updateApiKey(String apiKeyId, RequestOptions requestOptions) {
        return this.rawClient.updateApiKey(apiKeyId, requestOptions).body();
    }

    public UpdateApiKeyResponse updateApiKey(String apiKeyId, UpdateApiKeyRequestBody request) {
        return this.rawClient.updateApiKey(apiKeyId, request).body();
    }

    public UpdateApiKeyResponse updateApiKey(
            String apiKeyId, UpdateApiKeyRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.updateApiKey(apiKeyId, request, requestOptions).body();
    }

    public DeleteApiKeyResponse deleteApiKey(String apiKeyId) {
        return this.rawClient.deleteApiKey(apiKeyId).body();
    }

    public DeleteApiKeyResponse deleteApiKey(String apiKeyId, RequestOptions requestOptions) {
        return this.rawClient.deleteApiKey(apiKeyId, requestOptions).body();
    }

    public CountApiKeysResponse countApiKeys(CountApiKeysRequest request) {
        return this.rawClient.countApiKeys(request).body();
    }

    public CountApiKeysResponse countApiKeys(CountApiKeysRequest request, RequestOptions requestOptions) {
        return this.rawClient.countApiKeys(request, requestOptions).body();
    }

    public ListAuditLogsResponse listAuditLogs() {
        return this.rawClient.listAuditLogs().body();
    }

    public ListAuditLogsResponse listAuditLogs(RequestOptions requestOptions) {
        return this.rawClient.listAuditLogs(requestOptions).body();
    }

    public ListAuditLogsResponse listAuditLogs(ListAuditLogsRequest request) {
        return this.rawClient.listAuditLogs(request).body();
    }

    public ListAuditLogsResponse listAuditLogs(ListAuditLogsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listAuditLogs(request, requestOptions).body();
    }

    public GetAuditLogResponse getAuditLog(String auditLogId) {
        return this.rawClient.getAuditLog(auditLogId).body();
    }

    public GetAuditLogResponse getAuditLog(String auditLogId, RequestOptions requestOptions) {
        return this.rawClient.getAuditLog(auditLogId, requestOptions).body();
    }

    public CountAuditLogsResponse countAuditLogs() {
        return this.rawClient.countAuditLogs().body();
    }

    public CountAuditLogsResponse countAuditLogs(RequestOptions requestOptions) {
        return this.rawClient.countAuditLogs(requestOptions).body();
    }

    public CountAuditLogsResponse countAuditLogs(CountAuditLogsRequest request) {
        return this.rawClient.countAuditLogs(request).body();
    }

    public CountAuditLogsResponse countAuditLogs(CountAuditLogsRequest request, RequestOptions requestOptions) {
        return this.rawClient.countAuditLogs(request, requestOptions).body();
    }

    public ListEnvironmentsResponse listEnvironments() {
        return this.rawClient.listEnvironments().body();
    }

    public ListEnvironmentsResponse listEnvironments(RequestOptions requestOptions) {
        return this.rawClient.listEnvironments(requestOptions).body();
    }

    public ListEnvironmentsResponse listEnvironments(ListEnvironmentsRequest request) {
        return this.rawClient.listEnvironments(request).body();
    }

    public ListEnvironmentsResponse listEnvironments(ListEnvironmentsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listEnvironments(request, requestOptions).body();
    }

    public CreateEnvironmentResponse createEnvironment(CreateEnvironmentRequestBody request) {
        return this.rawClient.createEnvironment(request).body();
    }

    public CreateEnvironmentResponse createEnvironment(
            CreateEnvironmentRequestBody request, RequestOptions requestOptions) {
        return this.rawClient.createEnvironment(request, requestOptions).body();
    }

    public GetEnvironmentResponse getEnvironment(String environmentId) {
        return this.rawClient.getEnvironment(environmentId).body();
    }

    public GetEnvironmentResponse getEnvironment(String environmentId, RequestOptions requestOptions) {
        return this.rawClient.getEnvironment(environmentId, requestOptions).body();
    }

    public UpdateEnvironmentResponse updateEnvironment(String environmentId) {
        return this.rawClient.updateEnvironment(environmentId).body();
    }

    public UpdateEnvironmentResponse updateEnvironment(String environmentId, RequestOptions requestOptions) {
        return this.rawClient.updateEnvironment(environmentId, requestOptions).body();
    }

    public UpdateEnvironmentResponse updateEnvironment(String environmentId, UpdateEnvironmentRequestBody request) {
        return this.rawClient.updateEnvironment(environmentId, request).body();
    }

    public UpdateEnvironmentResponse updateEnvironment(
            String environmentId, UpdateEnvironmentRequestBody request, RequestOptions requestOptions) {
        return this.rawClient
                .updateEnvironment(environmentId, request, requestOptions)
                .body();
    }

    public DeleteEnvironmentResponse deleteEnvironment(String environmentId) {
        return this.rawClient.deleteEnvironment(environmentId).body();
    }

    public DeleteEnvironmentResponse deleteEnvironment(String environmentId, RequestOptions requestOptions) {
        return this.rawClient.deleteEnvironment(environmentId, requestOptions).body();
    }

    public QuickstartResponse quickstart() {
        return this.rawClient.quickstart().body();
    }

    public QuickstartResponse quickstart(RequestOptions requestOptions) {
        return this.rawClient.quickstart(requestOptions).body();
    }

    public GetWhoAmIResponse getWhoAmI() {
        return this.rawClient.getWhoAmI().body();
    }

    public GetWhoAmIResponse getWhoAmI(RequestOptions requestOptions) {
        return this.rawClient.getWhoAmI(requestOptions).body();
    }
}
