/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.credits.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CountCreditLedgerResponseParamsPeriod {
    public static final CountCreditLedgerResponseParamsPeriod RAW =
            new CountCreditLedgerResponseParamsPeriod(Value.RAW, "raw");

    public static final CountCreditLedgerResponseParamsPeriod MONTHLY =
            new CountCreditLedgerResponseParamsPeriod(Value.MONTHLY, "monthly");

    public static final CountCreditLedgerResponseParamsPeriod DAILY =
            new CountCreditLedgerResponseParamsPeriod(Value.DAILY, "daily");

    public static final CountCreditLedgerResponseParamsPeriod WEEKLY =
            new CountCreditLedgerResponseParamsPeriod(Value.WEEKLY, "weekly");

    private final Value value;

    private final String string;

    CountCreditLedgerResponseParamsPeriod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CountCreditLedgerResponseParamsPeriod
                        && this.string.equals(((CountCreditLedgerResponseParamsPeriod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case RAW:
                return visitor.visitRaw();
            case MONTHLY:
                return visitor.visitMonthly();
            case DAILY:
                return visitor.visitDaily();
            case WEEKLY:
                return visitor.visitWeekly();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CountCreditLedgerResponseParamsPeriod valueOf(String value) {
        switch (value) {
            case "raw":
                return RAW;
            case "monthly":
                return MONTHLY;
            case "daily":
                return DAILY;
            case "weekly":
                return WEEKLY;
            default:
                return new CountCreditLedgerResponseParamsPeriod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DAILY,

        WEEKLY,

        MONTHLY,

        RAW,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDaily();

        T visitWeekly();

        T visitMonthly();

        T visitRaw();

        T visitUnknown(String unknownType);
    }
}
