/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.credits.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeleteBillingPlanCreditGrantParams.Builder.class)
public final class DeleteBillingPlanCreditGrantParams {
    private final Optional<Boolean> applyToExisting;

    private final Map<String, Object> additionalProperties;

    private DeleteBillingPlanCreditGrantParams(
            Optional<Boolean> applyToExisting, Map<String, Object> additionalProperties) {
        this.applyToExisting = applyToExisting;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("apply_to_existing")
    public Optional<Boolean> getApplyToExisting() {
        return applyToExisting;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeleteBillingPlanCreditGrantParams
                && equalTo((DeleteBillingPlanCreditGrantParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeleteBillingPlanCreditGrantParams other) {
        return applyToExisting.equals(other.applyToExisting);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.applyToExisting);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> applyToExisting = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DeleteBillingPlanCreditGrantParams other) {
            applyToExisting(other.getApplyToExisting());
            return this;
        }

        @JsonSetter(value = "apply_to_existing", nulls = Nulls.SKIP)
        public Builder applyToExisting(Optional<Boolean> applyToExisting) {
            this.applyToExisting = applyToExisting;
            return this;
        }

        public Builder applyToExisting(Boolean applyToExisting) {
            this.applyToExisting = Optional.ofNullable(applyToExisting);
            return this;
        }

        public DeleteBillingPlanCreditGrantParams build() {
            return new DeleteBillingPlanCreditGrantParams(applyToExisting, additionalProperties);
        }
    }
}
