/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.credits.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import com.schematic.api.types.BillingCreditBundleStatus;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListCreditBundlesParams.Builder.class)
public final class ListCreditBundlesParams {
    private final Optional<String> bundleType;

    private final Optional<String> creditId;

    private final Optional<List<String>> ids;

    private final Optional<Long> limit;

    private final Optional<Long> offset;

    private final Optional<BillingCreditBundleStatus> status;

    private final Map<String, Object> additionalProperties;

    private ListCreditBundlesParams(
            Optional<String> bundleType,
            Optional<String> creditId,
            Optional<List<String>> ids,
            Optional<Long> limit,
            Optional<Long> offset,
            Optional<BillingCreditBundleStatus> status,
            Map<String, Object> additionalProperties) {
        this.bundleType = bundleType;
        this.creditId = creditId;
        this.ids = ids;
        this.limit = limit;
        this.offset = offset;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("bundle_type")
    public Optional<String> getBundleType() {
        return bundleType;
    }

    @JsonProperty("credit_id")
    public Optional<String> getCreditId() {
        return creditId;
    }

    @JsonProperty("ids")
    public Optional<List<String>> getIds() {
        return ids;
    }

    /**
     * @return Page limit (default 100)
     */
    @JsonProperty("limit")
    public Optional<Long> getLimit() {
        return limit;
    }

    /**
     * @return Page offset (default 0)
     */
    @JsonProperty("offset")
    public Optional<Long> getOffset() {
        return offset;
    }

    @JsonProperty("status")
    public Optional<BillingCreditBundleStatus> getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListCreditBundlesParams && equalTo((ListCreditBundlesParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListCreditBundlesParams other) {
        return bundleType.equals(other.bundleType)
                && creditId.equals(other.creditId)
                && ids.equals(other.ids)
                && limit.equals(other.limit)
                && offset.equals(other.offset)
                && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.bundleType, this.creditId, this.ids, this.limit, this.offset, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> bundleType = Optional.empty();

        private Optional<String> creditId = Optional.empty();

        private Optional<List<String>> ids = Optional.empty();

        private Optional<Long> limit = Optional.empty();

        private Optional<Long> offset = Optional.empty();

        private Optional<BillingCreditBundleStatus> status = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListCreditBundlesParams other) {
            bundleType(other.getBundleType());
            creditId(other.getCreditId());
            ids(other.getIds());
            limit(other.getLimit());
            offset(other.getOffset());
            status(other.getStatus());
            return this;
        }

        @JsonSetter(value = "bundle_type", nulls = Nulls.SKIP)
        public Builder bundleType(Optional<String> bundleType) {
            this.bundleType = bundleType;
            return this;
        }

        public Builder bundleType(String bundleType) {
            this.bundleType = Optional.ofNullable(bundleType);
            return this;
        }

        @JsonSetter(value = "credit_id", nulls = Nulls.SKIP)
        public Builder creditId(Optional<String> creditId) {
            this.creditId = creditId;
            return this;
        }

        public Builder creditId(String creditId) {
            this.creditId = Optional.ofNullable(creditId);
            return this;
        }

        @JsonSetter(value = "ids", nulls = Nulls.SKIP)
        public Builder ids(Optional<List<String>> ids) {
            this.ids = ids;
            return this;
        }

        public Builder ids(List<String> ids) {
            this.ids = Optional.ofNullable(ids);
            return this;
        }

        /**
         * <p>Page limit (default 100)</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Long> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Long limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Page offset (default 0)</p>
         */
        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public Builder offset(Optional<Long> offset) {
            this.offset = offset;
            return this;
        }

        public Builder offset(Long offset) {
            this.offset = Optional.ofNullable(offset);
            return this;
        }

        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<BillingCreditBundleStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(BillingCreditBundleStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        public ListCreditBundlesParams build() {
            return new ListCreditBundlesParams(bundleType, creditId, ids, limit, offset, status, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
