/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.credits.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListCompanyGrantsRequestDir {
    public static final ListCompanyGrantsRequestDir ASC = new ListCompanyGrantsRequestDir(Value.ASC, "asc");

    public static final ListCompanyGrantsRequestDir DESC = new ListCompanyGrantsRequestDir(Value.DESC, "desc");

    private final Value value;

    private final String string;

    ListCompanyGrantsRequestDir(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListCompanyGrantsRequestDir
                        && this.string.equals(((ListCompanyGrantsRequestDir) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ASC:
                return visitor.visitAsc();
            case DESC:
                return visitor.visitDesc();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListCompanyGrantsRequestDir valueOf(String value) {
        switch (value) {
            case "asc":
                return ASC;
            case "desc":
                return DESC;
            default:
                return new ListCompanyGrantsRequestDir(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ASC,

        DESC,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAsc();

        T visitDesc();

        T visitUnknown(String unknownType);
    }
}
