/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.credits.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import com.schematic.api.types.CreditGrantSortOrder;
import com.schematic.api.types.SortDirection;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListCompanyGrantsParams.Builder.class)
public final class ListCompanyGrantsParams {
    private final Optional<String> companyId;

    private final Optional<SortDirection> dir;

    private final Optional<Long> limit;

    private final Optional<Long> offset;

    private final Optional<CreditGrantSortOrder> order;

    private final Map<String, Object> additionalProperties;

    private ListCompanyGrantsParams(
            Optional<String> companyId,
            Optional<SortDirection> dir,
            Optional<Long> limit,
            Optional<Long> offset,
            Optional<CreditGrantSortOrder> order,
            Map<String, Object> additionalProperties) {
        this.companyId = companyId;
        this.dir = dir;
        this.limit = limit;
        this.offset = offset;
        this.order = order;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("company_id")
    public Optional<String> getCompanyId() {
        return companyId;
    }

    @JsonProperty("dir")
    public Optional<SortDirection> getDir() {
        return dir;
    }

    /**
     * @return Page limit (default 100)
     */
    @JsonProperty("limit")
    public Optional<Long> getLimit() {
        return limit;
    }

    /**
     * @return Page offset (default 0)
     */
    @JsonProperty("offset")
    public Optional<Long> getOffset() {
        return offset;
    }

    @JsonProperty("order")
    public Optional<CreditGrantSortOrder> getOrder() {
        return order;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListCompanyGrantsParams && equalTo((ListCompanyGrantsParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListCompanyGrantsParams other) {
        return companyId.equals(other.companyId)
                && dir.equals(other.dir)
                && limit.equals(other.limit)
                && offset.equals(other.offset)
                && order.equals(other.order);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.companyId, this.dir, this.limit, this.offset, this.order);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> companyId = Optional.empty();

        private Optional<SortDirection> dir = Optional.empty();

        private Optional<Long> limit = Optional.empty();

        private Optional<Long> offset = Optional.empty();

        private Optional<CreditGrantSortOrder> order = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListCompanyGrantsParams other) {
            companyId(other.getCompanyId());
            dir(other.getDir());
            limit(other.getLimit());
            offset(other.getOffset());
            order(other.getOrder());
            return this;
        }

        @JsonSetter(value = "company_id", nulls = Nulls.SKIP)
        public Builder companyId(Optional<String> companyId) {
            this.companyId = companyId;
            return this;
        }

        public Builder companyId(String companyId) {
            this.companyId = Optional.ofNullable(companyId);
            return this;
        }

        @JsonSetter(value = "dir", nulls = Nulls.SKIP)
        public Builder dir(Optional<SortDirection> dir) {
            this.dir = dir;
            return this;
        }

        public Builder dir(SortDirection dir) {
            this.dir = Optional.ofNullable(dir);
            return this;
        }

        /**
         * <p>Page limit (default 100)</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Long> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Long limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Page offset (default 0)</p>
         */
        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public Builder offset(Optional<Long> offset) {
            this.offset = offset;
            return this;
        }

        public Builder offset(Long offset) {
            this.offset = Optional.ofNullable(offset);
            return this;
        }

        @JsonSetter(value = "order", nulls = Nulls.SKIP)
        public Builder order(Optional<CreditGrantSortOrder> order) {
            this.order = order;
            return this;
        }

        public Builder order(CreditGrantSortOrder order) {
            this.order = Optional.ofNullable(order);
            return this;
        }

        public ListCompanyGrantsParams build() {
            return new ListCompanyGrantsParams(companyId, dir, limit, offset, order, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
