/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CheckoutFieldWithValue.Builder.class)
public final class CheckoutFieldWithValue {
    private final String definitionId;

    private final Optional<String> helperText;

    private final String id;

    private final String name;

    private final boolean required;

    private final String stripeMetadataKey;

    private final Optional<String> value;

    private final Map<String, Object> additionalProperties;

    private CheckoutFieldWithValue(
            String definitionId,
            Optional<String> helperText,
            String id,
            String name,
            boolean required,
            String stripeMetadataKey,
            Optional<String> value,
            Map<String, Object> additionalProperties) {
        this.definitionId = definitionId;
        this.helperText = helperText;
        this.id = id;
        this.name = name;
        this.required = required;
        this.stripeMetadataKey = stripeMetadataKey;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("definition_id")
    public String getDefinitionId() {
        return definitionId;
    }

    @JsonProperty("helper_text")
    public Optional<String> getHelperText() {
        return helperText;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("required")
    public boolean getRequired() {
        return required;
    }

    @JsonProperty("stripe_metadata_key")
    public String getStripeMetadataKey() {
        return stripeMetadataKey;
    }

    @JsonProperty("value")
    public Optional<String> getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CheckoutFieldWithValue && equalTo((CheckoutFieldWithValue) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CheckoutFieldWithValue other) {
        return definitionId.equals(other.definitionId)
                && helperText.equals(other.helperText)
                && id.equals(other.id)
                && name.equals(other.name)
                && required == other.required
                && stripeMetadataKey.equals(other.stripeMetadataKey)
                && value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.definitionId,
                this.helperText,
                this.id,
                this.name,
                this.required,
                this.stripeMetadataKey,
                this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DefinitionIdStage builder() {
        return new Builder();
    }

    public interface DefinitionIdStage {
        IdStage definitionId(@NotNull String definitionId);

        Builder from(CheckoutFieldWithValue other);
    }

    public interface IdStage {
        NameStage id(@NotNull String id);
    }

    public interface NameStage {
        RequiredStage name(@NotNull String name);
    }

    public interface RequiredStage {
        StripeMetadataKeyStage required(boolean required);
    }

    public interface StripeMetadataKeyStage {
        _FinalStage stripeMetadataKey(@NotNull String stripeMetadataKey);
    }

    public interface _FinalStage {
        CheckoutFieldWithValue build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage helperText(Optional<String> helperText);

        _FinalStage helperText(String helperText);

        _FinalStage value(Optional<String> value);

        _FinalStage value(String value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements DefinitionIdStage, IdStage, NameStage, RequiredStage, StripeMetadataKeyStage, _FinalStage {
        private String definitionId;

        private String id;

        private String name;

        private boolean required;

        private String stripeMetadataKey;

        private Optional<String> value = Optional.empty();

        private Optional<String> helperText = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CheckoutFieldWithValue other) {
            definitionId(other.getDefinitionId());
            helperText(other.getHelperText());
            id(other.getId());
            name(other.getName());
            required(other.getRequired());
            stripeMetadataKey(other.getStripeMetadataKey());
            value(other.getValue());
            return this;
        }

        @java.lang.Override
        @JsonSetter("definition_id")
        public IdStage definitionId(@NotNull String definitionId) {
            this.definitionId = Objects.requireNonNull(definitionId, "definitionId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public RequiredStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("required")
        public StripeMetadataKeyStage required(boolean required) {
            this.required = required;
            return this;
        }

        @java.lang.Override
        @JsonSetter("stripe_metadata_key")
        public _FinalStage stripeMetadataKey(@NotNull String stripeMetadataKey) {
            this.stripeMetadataKey = Objects.requireNonNull(stripeMetadataKey, "stripeMetadataKey must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage value(String value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public _FinalStage value(Optional<String> value) {
            this.value = value;
            return this;
        }

        @java.lang.Override
        public _FinalStage helperText(String helperText) {
            this.helperText = Optional.ofNullable(helperText);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "helper_text", nulls = Nulls.SKIP)
        public _FinalStage helperText(Optional<String> helperText) {
            this.helperText = helperText;
            return this;
        }

        @java.lang.Override
        public CheckoutFieldWithValue build() {
            return new CheckoutFieldWithValue(
                    definitionId, helperText, id, name, required, stripeMetadataKey, value, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
