/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CheckFlagResponseData.Builder.class)
public final class CheckFlagResponseData {
    private final Optional<String> companyId;

    private final Optional<FeatureEntitlement> entitlement;

    private final Optional<String> error;

    private final Optional<Long> featureAllocation;

    private final Optional<Long> featureUsage;

    private final Optional<String> featureUsageEvent;

    private final Optional<MetricPeriod> featureUsagePeriod;

    private final Optional<OffsetDateTime> featureUsageResetAt;

    private final String flag;

    private final Optional<String> flagId;

    private final String reason;

    private final Optional<String> ruleId;

    private final Optional<RuleType> ruleType;

    private final Optional<String> userId;

    private final boolean value;

    private final Map<String, Object> additionalProperties;

    private CheckFlagResponseData(
            Optional<String> companyId,
            Optional<FeatureEntitlement> entitlement,
            Optional<String> error,
            Optional<Long> featureAllocation,
            Optional<Long> featureUsage,
            Optional<String> featureUsageEvent,
            Optional<MetricPeriod> featureUsagePeriod,
            Optional<OffsetDateTime> featureUsageResetAt,
            String flag,
            Optional<String> flagId,
            String reason,
            Optional<String> ruleId,
            Optional<RuleType> ruleType,
            Optional<String> userId,
            boolean value,
            Map<String, Object> additionalProperties) {
        this.companyId = companyId;
        this.entitlement = entitlement;
        this.error = error;
        this.featureAllocation = featureAllocation;
        this.featureUsage = featureUsage;
        this.featureUsageEvent = featureUsageEvent;
        this.featureUsagePeriod = featureUsagePeriod;
        this.featureUsageResetAt = featureUsageResetAt;
        this.flag = flag;
        this.flagId = flagId;
        this.reason = reason;
        this.ruleId = ruleId;
        this.ruleType = ruleType;
        this.userId = userId;
        this.value = value;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return If company keys were provided and matched a company, its ID
     */
    @JsonProperty("company_id")
    public Optional<String> getCompanyId() {
        return companyId;
    }

    /**
     * @return If a feature entitlement rule was matched, its entitlement details
     */
    @JsonProperty("entitlement")
    public Optional<FeatureEntitlement> getEntitlement() {
        return entitlement;
    }

    /**
     * @return If an error occurred while checking the flag, the error message
     */
    @JsonProperty("error")
    public Optional<String> getError() {
        return error;
    }

    /**
     * @return Deprecated: Use Entitlement.Allocation instead.
     */
    @JsonProperty("feature_allocation")
    public Optional<Long> getFeatureAllocation() {
        return featureAllocation;
    }

    /**
     * @return Deprecated: Use Entitlement.Usage instead.
     */
    @JsonProperty("feature_usage")
    public Optional<Long> getFeatureUsage() {
        return featureUsage;
    }

    /**
     * @return Deprecated: Use Entitlement.EventName instead.
     */
    @JsonProperty("feature_usage_event")
    public Optional<String> getFeatureUsageEvent() {
        return featureUsageEvent;
    }

    /**
     * @return Deprecated: Use Entitlement.MetricPeriod instead.
     */
    @JsonProperty("feature_usage_period")
    public Optional<MetricPeriod> getFeatureUsagePeriod() {
        return featureUsagePeriod;
    }

    /**
     * @return Deprecated: Use Entitlement.MetricResetAt instead.
     */
    @JsonProperty("feature_usage_reset_at")
    public Optional<OffsetDateTime> getFeatureUsageResetAt() {
        return featureUsageResetAt;
    }

    /**
     * @return The key used to check the flag
     */
    @JsonProperty("flag")
    public String getFlag() {
        return flag;
    }

    /**
     * @return If a flag was found, its ID
     */
    @JsonProperty("flag_id")
    public Optional<String> getFlagId() {
        return flagId;
    }

    /**
     * @return A human-readable explanation of the result
     */
    @JsonProperty("reason")
    public String getReason() {
        return reason;
    }

    /**
     * @return If a rule was found, its ID
     */
    @JsonProperty("rule_id")
    public Optional<String> getRuleId() {
        return ruleId;
    }

    /**
     * @return If a rule was found, its type
     */
    @JsonProperty("rule_type")
    public Optional<RuleType> getRuleType() {
        return ruleType;
    }

    /**
     * @return If user keys were provided and matched a user, its ID
     */
    @JsonProperty("user_id")
    public Optional<String> getUserId() {
        return userId;
    }

    /**
     * @return A boolean flag check result; for feature entitlements, this represents whether further consumption of the feature is permitted
     */
    @JsonProperty("value")
    public boolean getValue() {
        return value;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CheckFlagResponseData && equalTo((CheckFlagResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CheckFlagResponseData other) {
        return companyId.equals(other.companyId)
                && entitlement.equals(other.entitlement)
                && error.equals(other.error)
                && featureAllocation.equals(other.featureAllocation)
                && featureUsage.equals(other.featureUsage)
                && featureUsageEvent.equals(other.featureUsageEvent)
                && featureUsagePeriod.equals(other.featureUsagePeriod)
                && featureUsageResetAt.equals(other.featureUsageResetAt)
                && flag.equals(other.flag)
                && flagId.equals(other.flagId)
                && reason.equals(other.reason)
                && ruleId.equals(other.ruleId)
                && ruleType.equals(other.ruleType)
                && userId.equals(other.userId)
                && value == other.value;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.companyId,
                this.entitlement,
                this.error,
                this.featureAllocation,
                this.featureUsage,
                this.featureUsageEvent,
                this.featureUsagePeriod,
                this.featureUsageResetAt,
                this.flag,
                this.flagId,
                this.reason,
                this.ruleId,
                this.ruleType,
                this.userId,
                this.value);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FlagStage builder() {
        return new Builder();
    }

    public interface FlagStage {
        /**
         * <p>The key used to check the flag</p>
         */
        ReasonStage flag(@NotNull String flag);

        Builder from(CheckFlagResponseData other);
    }

    public interface ReasonStage {
        /**
         * <p>A human-readable explanation of the result</p>
         */
        ValueStage reason(@NotNull String reason);
    }

    public interface ValueStage {
        /**
         * <p>A boolean flag check result; for feature entitlements, this represents whether further consumption of the feature is permitted</p>
         */
        _FinalStage value(boolean value);
    }

    public interface _FinalStage {
        CheckFlagResponseData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>If company keys were provided and matched a company, its ID</p>
         */
        _FinalStage companyId(Optional<String> companyId);

        _FinalStage companyId(String companyId);

        /**
         * <p>If a feature entitlement rule was matched, its entitlement details</p>
         */
        _FinalStage entitlement(Optional<FeatureEntitlement> entitlement);

        _FinalStage entitlement(FeatureEntitlement entitlement);

        /**
         * <p>If an error occurred while checking the flag, the error message</p>
         */
        _FinalStage error(Optional<String> error);

        _FinalStage error(String error);

        /**
         * <p>Deprecated: Use Entitlement.Allocation instead.</p>
         */
        _FinalStage featureAllocation(Optional<Long> featureAllocation);

        _FinalStage featureAllocation(Long featureAllocation);

        /**
         * <p>Deprecated: Use Entitlement.Usage instead.</p>
         */
        _FinalStage featureUsage(Optional<Long> featureUsage);

        _FinalStage featureUsage(Long featureUsage);

        /**
         * <p>Deprecated: Use Entitlement.EventName instead.</p>
         */
        _FinalStage featureUsageEvent(Optional<String> featureUsageEvent);

        _FinalStage featureUsageEvent(String featureUsageEvent);

        /**
         * <p>Deprecated: Use Entitlement.MetricPeriod instead.</p>
         */
        _FinalStage featureUsagePeriod(Optional<MetricPeriod> featureUsagePeriod);

        _FinalStage featureUsagePeriod(MetricPeriod featureUsagePeriod);

        /**
         * <p>Deprecated: Use Entitlement.MetricResetAt instead.</p>
         */
        _FinalStage featureUsageResetAt(Optional<OffsetDateTime> featureUsageResetAt);

        _FinalStage featureUsageResetAt(OffsetDateTime featureUsageResetAt);

        /**
         * <p>If a flag was found, its ID</p>
         */
        _FinalStage flagId(Optional<String> flagId);

        _FinalStage flagId(String flagId);

        /**
         * <p>If a rule was found, its ID</p>
         */
        _FinalStage ruleId(Optional<String> ruleId);

        _FinalStage ruleId(String ruleId);

        /**
         * <p>If a rule was found, its type</p>
         */
        _FinalStage ruleType(Optional<RuleType> ruleType);

        _FinalStage ruleType(RuleType ruleType);

        /**
         * <p>If user keys were provided and matched a user, its ID</p>
         */
        _FinalStage userId(Optional<String> userId);

        _FinalStage userId(String userId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FlagStage, ReasonStage, ValueStage, _FinalStage {
        private String flag;

        private String reason;

        private boolean value;

        private Optional<String> userId = Optional.empty();

        private Optional<RuleType> ruleType = Optional.empty();

        private Optional<String> ruleId = Optional.empty();

        private Optional<String> flagId = Optional.empty();

        private Optional<OffsetDateTime> featureUsageResetAt = Optional.empty();

        private Optional<MetricPeriod> featureUsagePeriod = Optional.empty();

        private Optional<String> featureUsageEvent = Optional.empty();

        private Optional<Long> featureUsage = Optional.empty();

        private Optional<Long> featureAllocation = Optional.empty();

        private Optional<String> error = Optional.empty();

        private Optional<FeatureEntitlement> entitlement = Optional.empty();

        private Optional<String> companyId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CheckFlagResponseData other) {
            companyId(other.getCompanyId());
            entitlement(other.getEntitlement());
            error(other.getError());
            featureAllocation(other.getFeatureAllocation());
            featureUsage(other.getFeatureUsage());
            featureUsageEvent(other.getFeatureUsageEvent());
            featureUsagePeriod(other.getFeatureUsagePeriod());
            featureUsageResetAt(other.getFeatureUsageResetAt());
            flag(other.getFlag());
            flagId(other.getFlagId());
            reason(other.getReason());
            ruleId(other.getRuleId());
            ruleType(other.getRuleType());
            userId(other.getUserId());
            value(other.getValue());
            return this;
        }

        /**
         * <p>The key used to check the flag</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("flag")
        public ReasonStage flag(@NotNull String flag) {
            this.flag = Objects.requireNonNull(flag, "flag must not be null");
            return this;
        }

        /**
         * <p>A human-readable explanation of the result</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("reason")
        public ValueStage reason(@NotNull String reason) {
            this.reason = Objects.requireNonNull(reason, "reason must not be null");
            return this;
        }

        /**
         * <p>A boolean flag check result; for feature entitlements, this represents whether further consumption of the feature is permitted</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("value")
        public _FinalStage value(boolean value) {
            this.value = value;
            return this;
        }

        /**
         * <p>If user keys were provided and matched a user, its ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        /**
         * <p>If user keys were provided and matched a user, its ID</p>
         */
        @java.lang.Override
        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        /**
         * <p>If a rule was found, its type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage ruleType(RuleType ruleType) {
            this.ruleType = Optional.ofNullable(ruleType);
            return this;
        }

        /**
         * <p>If a rule was found, its type</p>
         */
        @java.lang.Override
        @JsonSetter(value = "rule_type", nulls = Nulls.SKIP)
        public _FinalStage ruleType(Optional<RuleType> ruleType) {
            this.ruleType = ruleType;
            return this;
        }

        /**
         * <p>If a rule was found, its ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage ruleId(String ruleId) {
            this.ruleId = Optional.ofNullable(ruleId);
            return this;
        }

        /**
         * <p>If a rule was found, its ID</p>
         */
        @java.lang.Override
        @JsonSetter(value = "rule_id", nulls = Nulls.SKIP)
        public _FinalStage ruleId(Optional<String> ruleId) {
            this.ruleId = ruleId;
            return this;
        }

        /**
         * <p>If a flag was found, its ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage flagId(String flagId) {
            this.flagId = Optional.ofNullable(flagId);
            return this;
        }

        /**
         * <p>If a flag was found, its ID</p>
         */
        @java.lang.Override
        @JsonSetter(value = "flag_id", nulls = Nulls.SKIP)
        public _FinalStage flagId(Optional<String> flagId) {
            this.flagId = flagId;
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.MetricResetAt instead.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage featureUsageResetAt(OffsetDateTime featureUsageResetAt) {
            this.featureUsageResetAt = Optional.ofNullable(featureUsageResetAt);
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.MetricResetAt instead.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "feature_usage_reset_at", nulls = Nulls.SKIP)
        public _FinalStage featureUsageResetAt(Optional<OffsetDateTime> featureUsageResetAt) {
            this.featureUsageResetAt = featureUsageResetAt;
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.MetricPeriod instead.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage featureUsagePeriod(MetricPeriod featureUsagePeriod) {
            this.featureUsagePeriod = Optional.ofNullable(featureUsagePeriod);
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.MetricPeriod instead.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "feature_usage_period", nulls = Nulls.SKIP)
        public _FinalStage featureUsagePeriod(Optional<MetricPeriod> featureUsagePeriod) {
            this.featureUsagePeriod = featureUsagePeriod;
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.EventName instead.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage featureUsageEvent(String featureUsageEvent) {
            this.featureUsageEvent = Optional.ofNullable(featureUsageEvent);
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.EventName instead.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "feature_usage_event", nulls = Nulls.SKIP)
        public _FinalStage featureUsageEvent(Optional<String> featureUsageEvent) {
            this.featureUsageEvent = featureUsageEvent;
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.Usage instead.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage featureUsage(Long featureUsage) {
            this.featureUsage = Optional.ofNullable(featureUsage);
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.Usage instead.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "feature_usage", nulls = Nulls.SKIP)
        public _FinalStage featureUsage(Optional<Long> featureUsage) {
            this.featureUsage = featureUsage;
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.Allocation instead.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage featureAllocation(Long featureAllocation) {
            this.featureAllocation = Optional.ofNullable(featureAllocation);
            return this;
        }

        /**
         * <p>Deprecated: Use Entitlement.Allocation instead.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "feature_allocation", nulls = Nulls.SKIP)
        public _FinalStage featureAllocation(Optional<Long> featureAllocation) {
            this.featureAllocation = featureAllocation;
            return this;
        }

        /**
         * <p>If an error occurred while checking the flag, the error message</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage error(String error) {
            this.error = Optional.ofNullable(error);
            return this;
        }

        /**
         * <p>If an error occurred while checking the flag, the error message</p>
         */
        @java.lang.Override
        @JsonSetter(value = "error", nulls = Nulls.SKIP)
        public _FinalStage error(Optional<String> error) {
            this.error = error;
            return this;
        }

        /**
         * <p>If a feature entitlement rule was matched, its entitlement details</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage entitlement(FeatureEntitlement entitlement) {
            this.entitlement = Optional.ofNullable(entitlement);
            return this;
        }

        /**
         * <p>If a feature entitlement rule was matched, its entitlement details</p>
         */
        @java.lang.Override
        @JsonSetter(value = "entitlement", nulls = Nulls.SKIP)
        public _FinalStage entitlement(Optional<FeatureEntitlement> entitlement) {
            this.entitlement = entitlement;
            return this;
        }

        /**
         * <p>If company keys were provided and matched a company, its ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage companyId(String companyId) {
            this.companyId = Optional.ofNullable(companyId);
            return this;
        }

        /**
         * <p>If company keys were provided and matched a company, its ID</p>
         */
        @java.lang.Override
        @JsonSetter(value = "company_id", nulls = Nulls.SKIP)
        public _FinalStage companyId(Optional<String> companyId) {
            this.companyId = companyId;
            return this;
        }

        @java.lang.Override
        public CheckFlagResponseData build() {
            return new CheckFlagResponseData(
                    companyId,
                    entitlement,
                    error,
                    featureAllocation,
                    featureUsage,
                    featureUsageEvent,
                    featureUsagePeriod,
                    featureUsageResetAt,
                    flag,
                    flagId,
                    reason,
                    ruleId,
                    ruleType,
                    userId,
                    value,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
