/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomPlanBillingResponseData.Builder.class)
public final class CustomPlanBillingResponseData {
    private final CustomPlanActivationStrategy activationStrategy;

    private final String companyId;

    private final OffsetDateTime createdAt;

    private final long daysUntilDue;

    private final String id;

    private final Optional<OffsetDateTime> paidAt;

    private final String planId;

    private final Optional<OffsetDateTime> publishedAt;

    private final CustomPlanBillingStatus status;

    private final Optional<String> stripeInvoiceUrl;

    private final OffsetDateTime updatedAt;

    private final Map<String, Object> additionalProperties;

    private CustomPlanBillingResponseData(
            CustomPlanActivationStrategy activationStrategy,
            String companyId,
            OffsetDateTime createdAt,
            long daysUntilDue,
            String id,
            Optional<OffsetDateTime> paidAt,
            String planId,
            Optional<OffsetDateTime> publishedAt,
            CustomPlanBillingStatus status,
            Optional<String> stripeInvoiceUrl,
            OffsetDateTime updatedAt,
            Map<String, Object> additionalProperties) {
        this.activationStrategy = activationStrategy;
        this.companyId = companyId;
        this.createdAt = createdAt;
        this.daysUntilDue = daysUntilDue;
        this.id = id;
        this.paidAt = paidAt;
        this.planId = planId;
        this.publishedAt = publishedAt;
        this.status = status;
        this.stripeInvoiceUrl = stripeInvoiceUrl;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("activation_strategy")
    public CustomPlanActivationStrategy getActivationStrategy() {
        return activationStrategy;
    }

    @JsonProperty("company_id")
    public String getCompanyId() {
        return companyId;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("days_until_due")
    public long getDaysUntilDue() {
        return daysUntilDue;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("paid_at")
    public Optional<OffsetDateTime> getPaidAt() {
        return paidAt;
    }

    @JsonProperty("plan_id")
    public String getPlanId() {
        return planId;
    }

    @JsonProperty("published_at")
    public Optional<OffsetDateTime> getPublishedAt() {
        return publishedAt;
    }

    @JsonProperty("status")
    public CustomPlanBillingStatus getStatus() {
        return status;
    }

    @JsonProperty("stripe_invoice_url")
    public Optional<String> getStripeInvoiceUrl() {
        return stripeInvoiceUrl;
    }

    @JsonProperty("updated_at")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomPlanBillingResponseData && equalTo((CustomPlanBillingResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomPlanBillingResponseData other) {
        return activationStrategy.equals(other.activationStrategy)
                && companyId.equals(other.companyId)
                && createdAt.equals(other.createdAt)
                && daysUntilDue == other.daysUntilDue
                && id.equals(other.id)
                && paidAt.equals(other.paidAt)
                && planId.equals(other.planId)
                && publishedAt.equals(other.publishedAt)
                && status.equals(other.status)
                && stripeInvoiceUrl.equals(other.stripeInvoiceUrl)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.activationStrategy,
                this.companyId,
                this.createdAt,
                this.daysUntilDue,
                this.id,
                this.paidAt,
                this.planId,
                this.publishedAt,
                this.status,
                this.stripeInvoiceUrl,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActivationStrategyStage builder() {
        return new Builder();
    }

    public interface ActivationStrategyStage {
        CompanyIdStage activationStrategy(@NotNull CustomPlanActivationStrategy activationStrategy);

        Builder from(CustomPlanBillingResponseData other);
    }

    public interface CompanyIdStage {
        CreatedAtStage companyId(@NotNull String companyId);
    }

    public interface CreatedAtStage {
        DaysUntilDueStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface DaysUntilDueStage {
        IdStage daysUntilDue(long daysUntilDue);
    }

    public interface IdStage {
        PlanIdStage id(@NotNull String id);
    }

    public interface PlanIdStage {
        StatusStage planId(@NotNull String planId);
    }

    public interface StatusStage {
        UpdatedAtStage status(@NotNull CustomPlanBillingStatus status);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        CustomPlanBillingResponseData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage paidAt(Optional<OffsetDateTime> paidAt);

        _FinalStage paidAt(OffsetDateTime paidAt);

        _FinalStage publishedAt(Optional<OffsetDateTime> publishedAt);

        _FinalStage publishedAt(OffsetDateTime publishedAt);

        _FinalStage stripeInvoiceUrl(Optional<String> stripeInvoiceUrl);

        _FinalStage stripeInvoiceUrl(String stripeInvoiceUrl);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ActivationStrategyStage,
                    CompanyIdStage,
                    CreatedAtStage,
                    DaysUntilDueStage,
                    IdStage,
                    PlanIdStage,
                    StatusStage,
                    UpdatedAtStage,
                    _FinalStage {
        private CustomPlanActivationStrategy activationStrategy;

        private String companyId;

        private OffsetDateTime createdAt;

        private long daysUntilDue;

        private String id;

        private String planId;

        private CustomPlanBillingStatus status;

        private OffsetDateTime updatedAt;

        private Optional<String> stripeInvoiceUrl = Optional.empty();

        private Optional<OffsetDateTime> publishedAt = Optional.empty();

        private Optional<OffsetDateTime> paidAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomPlanBillingResponseData other) {
            activationStrategy(other.getActivationStrategy());
            companyId(other.getCompanyId());
            createdAt(other.getCreatedAt());
            daysUntilDue(other.getDaysUntilDue());
            id(other.getId());
            paidAt(other.getPaidAt());
            planId(other.getPlanId());
            publishedAt(other.getPublishedAt());
            status(other.getStatus());
            stripeInvoiceUrl(other.getStripeInvoiceUrl());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("activation_strategy")
        public CompanyIdStage activationStrategy(@NotNull CustomPlanActivationStrategy activationStrategy) {
            this.activationStrategy = Objects.requireNonNull(activationStrategy, "activationStrategy must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("company_id")
        public CreatedAtStage companyId(@NotNull String companyId) {
            this.companyId = Objects.requireNonNull(companyId, "companyId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public DaysUntilDueStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("days_until_due")
        public IdStage daysUntilDue(long daysUntilDue) {
            this.daysUntilDue = daysUntilDue;
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public PlanIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("plan_id")
        public StatusStage planId(@NotNull String planId) {
            this.planId = Objects.requireNonNull(planId, "planId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public UpdatedAtStage status(@NotNull CustomPlanBillingStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage stripeInvoiceUrl(String stripeInvoiceUrl) {
            this.stripeInvoiceUrl = Optional.ofNullable(stripeInvoiceUrl);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "stripe_invoice_url", nulls = Nulls.SKIP)
        public _FinalStage stripeInvoiceUrl(Optional<String> stripeInvoiceUrl) {
            this.stripeInvoiceUrl = stripeInvoiceUrl;
            return this;
        }

        @java.lang.Override
        public _FinalStage publishedAt(OffsetDateTime publishedAt) {
            this.publishedAt = Optional.ofNullable(publishedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "published_at", nulls = Nulls.SKIP)
        public _FinalStage publishedAt(Optional<OffsetDateTime> publishedAt) {
            this.publishedAt = publishedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage paidAt(OffsetDateTime paidAt) {
            this.paidAt = Optional.ofNullable(paidAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "paid_at", nulls = Nulls.SKIP)
        public _FinalStage paidAt(Optional<OffsetDateTime> paidAt) {
            this.paidAt = paidAt;
            return this;
        }

        @java.lang.Override
        public CustomPlanBillingResponseData build() {
            return new CustomPlanBillingResponseData(
                    activationStrategy,
                    companyId,
                    createdAt,
                    daysUntilDue,
                    id,
                    paidAt,
                    planId,
                    publishedAt,
                    status,
                    stripeInvoiceUrl,
                    updatedAt,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
