/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DataExportOutputFileType {
    public static final DataExportOutputFileType CSV_GZ = new DataExportOutputFileType(Value.CSV_GZ, "csv.gz");

    public static final DataExportOutputFileType CSV = new DataExportOutputFileType(Value.CSV, "csv");

    private final Value value;

    private final String string;

    DataExportOutputFileType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DataExportOutputFileType
                        && this.string.equals(((DataExportOutputFileType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CSV_GZ:
                return visitor.visitCsvGz();
            case CSV:
                return visitor.visitCsv();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DataExportOutputFileType valueOf(String value) {
        switch (value) {
            case "csv.gz":
                return CSV_GZ;
            case "csv":
                return CSV;
            default:
                return new DataExportOutputFileType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CSV,

        CSV_GZ,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCsv();

        T visitCsvGz();

        T visitUnknown(String unknownType);
    }
}
