/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FeatureLifecyclePhase {
    public static final FeatureLifecyclePhase GA = new FeatureLifecyclePhase(Value.GA, "ga");

    public static final FeatureLifecyclePhase ALPHA = new FeatureLifecyclePhase(Value.ALPHA, "alpha");

    public static final FeatureLifecyclePhase BETA = new FeatureLifecyclePhase(Value.BETA, "beta");

    public static final FeatureLifecyclePhase INACTIVE = new FeatureLifecyclePhase(Value.INACTIVE, "inactive");

    public static final FeatureLifecyclePhase ADD_ON = new FeatureLifecyclePhase(Value.ADD_ON, "add_on");

    public static final FeatureLifecyclePhase DEPRECATED = new FeatureLifecyclePhase(Value.DEPRECATED, "deprecated");

    public static final FeatureLifecyclePhase LEGACY = new FeatureLifecyclePhase(Value.LEGACY, "legacy");

    public static final FeatureLifecyclePhase INTERNAL_TESTING =
            new FeatureLifecyclePhase(Value.INTERNAL_TESTING, "internal_testing");

    public static final FeatureLifecyclePhase IN_PLAN = new FeatureLifecyclePhase(Value.IN_PLAN, "in_plan");

    private final Value value;

    private final String string;

    FeatureLifecyclePhase(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof FeatureLifecyclePhase
                        && this.string.equals(((FeatureLifecyclePhase) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case GA:
                return visitor.visitGa();
            case ALPHA:
                return visitor.visitAlpha();
            case BETA:
                return visitor.visitBeta();
            case INACTIVE:
                return visitor.visitInactive();
            case ADD_ON:
                return visitor.visitAddOn();
            case DEPRECATED:
                return visitor.visitDeprecated();
            case LEGACY:
                return visitor.visitLegacy();
            case INTERNAL_TESTING:
                return visitor.visitInternalTesting();
            case IN_PLAN:
                return visitor.visitInPlan();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FeatureLifecyclePhase valueOf(String value) {
        switch (value) {
            case "ga":
                return GA;
            case "alpha":
                return ALPHA;
            case "beta":
                return BETA;
            case "inactive":
                return INACTIVE;
            case "add_on":
                return ADD_ON;
            case "deprecated":
                return DEPRECATED;
            case "legacy":
                return LEGACY;
            case "internal_testing":
                return INTERNAL_TESTING;
            case "in_plan":
                return IN_PLAN;
            default:
                return new FeatureLifecyclePhase(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ADD_ON,

        ALPHA,

        BETA,

        DEPRECATED,

        GA,

        INACTIVE,

        IN_PLAN,

        INTERNAL_TESTING,

        LEGACY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAddOn();

        T visitAlpha();

        T visitBeta();

        T visitDeprecated();

        T visitGa();

        T visitInactive();

        T visitInPlan();

        T visitInternalTesting();

        T visitLegacy();

        T visitUnknown(String unknownType);
    }
}
