/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PlanBundleAction {
    public static final PlanBundleAction UPDATE = new PlanBundleAction(Value.UPDATE, "update");

    public static final PlanBundleAction DELETE = new PlanBundleAction(Value.DELETE, "delete");

    public static final PlanBundleAction CREATE = new PlanBundleAction(Value.CREATE, "create");

    private final Value value;

    private final String string;

    PlanBundleAction(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PlanBundleAction && this.string.equals(((PlanBundleAction) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case UPDATE:
                return visitor.visitUpdate();
            case DELETE:
                return visitor.visitDelete();
            case CREATE:
                return visitor.visitCreate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PlanBundleAction valueOf(String value) {
        switch (value) {
            case "update":
                return UPDATE;
            case "delete":
                return DELETE;
            case "create":
                return CREATE;
            default:
                return new PlanBundleAction(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CREATE,

        UPDATE,

        DELETE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCreate();

        T visitUpdate();

        T visitDelete();

        T visitUnknown(String unknownType);
    }
}
