/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PlanVersionCompanyMigrationStatus {
    public static final PlanVersionCompanyMigrationStatus SKIPPED =
            new PlanVersionCompanyMigrationStatus(Value.SKIPPED, "skipped");

    public static final PlanVersionCompanyMigrationStatus FAILED =
            new PlanVersionCompanyMigrationStatus(Value.FAILED, "failed");

    public static final PlanVersionCompanyMigrationStatus COMPLETED =
            new PlanVersionCompanyMigrationStatus(Value.COMPLETED, "completed");

    public static final PlanVersionCompanyMigrationStatus IN_PROGRESS =
            new PlanVersionCompanyMigrationStatus(Value.IN_PROGRESS, "in_progress");

    public static final PlanVersionCompanyMigrationStatus PENDING =
            new PlanVersionCompanyMigrationStatus(Value.PENDING, "pending");

    private final Value value;

    private final String string;

    PlanVersionCompanyMigrationStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PlanVersionCompanyMigrationStatus
                        && this.string.equals(((PlanVersionCompanyMigrationStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SKIPPED:
                return visitor.visitSkipped();
            case FAILED:
                return visitor.visitFailed();
            case COMPLETED:
                return visitor.visitCompleted();
            case IN_PROGRESS:
                return visitor.visitInProgress();
            case PENDING:
                return visitor.visitPending();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PlanVersionCompanyMigrationStatus valueOf(String value) {
        switch (value) {
            case "skipped":
                return SKIPPED;
            case "failed":
                return FAILED;
            case "completed":
                return COMPLETED;
            case "in_progress":
                return IN_PROGRESS;
            case "pending":
                return PENDING;
            default:
                return new PlanVersionCompanyMigrationStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        COMPLETED,

        FAILED,

        IN_PROGRESS,

        PENDING,

        SKIPPED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCompleted();

        T visitFailed();

        T visitInProgress();

        T visitPending();

        T visitSkipped();

        T visitUnknown(String unknownType);
    }
}
