/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PlanControlledByType {
    public static final PlanControlledByType SCHEMATIC = new PlanControlledByType(Value.SCHEMATIC, "schematic");

    public static final PlanControlledByType STRIPE = new PlanControlledByType(Value.STRIPE, "stripe");

    private final Value value;

    private final String string;

    PlanControlledByType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PlanControlledByType && this.string.equals(((PlanControlledByType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case SCHEMATIC:
                return visitor.visitSchematic();
            case STRIPE:
                return visitor.visitStripe();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PlanControlledByType valueOf(String value) {
        switch (value) {
            case "schematic":
                return SCHEMATIC;
            case "stripe":
                return STRIPE;
            default:
                return new PlanControlledByType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SCHEMATIC,

        STRIPE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSchematic();

        T visitStripe();

        T visitUnknown(String unknownType);
    }
}
