/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PlanChangeResponseDataAction {
    CHECKOUT("checkout"),

    COMPANY_UPSERT("company_upsert"),

    FALLBACK_PLAN("fallback_plan"),

    MANAGE_PLAN("manage_plan"),

    PLAN_BILLING_PRODUCT_CHANGED("plan_billing_product_changed"),

    PLAN_DELETED("plan_deleted"),

    QUICKSTART("quickstart"),

    SUBSCRIPTION_CHANGE("subscription_change");

    private final String value;

    PlanChangeResponseDataAction(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
