/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PlanBillingSource {
    public static final PlanBillingSource CUSTOM_PLAN = new PlanBillingSource(Value.CUSTOM_PLAN, "custom_plan");

    public static final PlanBillingSource MANAGE_PLAN = new PlanBillingSource(Value.MANAGE_PLAN, "manage_plan");

    private final Value value;

    private final String string;

    PlanBillingSource(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PlanBillingSource && this.string.equals(((PlanBillingSource) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CUSTOM_PLAN:
                return visitor.visitCustomPlan();
            case MANAGE_PLAN:
                return visitor.visitManagePlan();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PlanBillingSource valueOf(String value) {
        switch (value) {
            case "custom_plan":
                return CUSTOM_PLAN;
            case "manage_plan":
                return MANAGE_PLAN;
            default:
                return new PlanBillingSource(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CUSTOM_PLAN,

        MANAGE_PLAN,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCustomPlan();

        T visitManagePlan();

        T visitUnknown(String unknownType);
    }
}
