/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PlanVersionResponseData.Builder.class)
public final class PlanVersionResponseData {
    private final OffsetDateTime createdAt;

    private final String description;

    private final String environmentId;

    private final String icon;

    private final String id;

    private final String name;

    private final Optional<String> originalPlanId;

    private final PlanType planType;

    private final PlanVersionStatus status;

    private final OffsetDateTime updatedAt;

    private final long version;

    private final Map<String, Object> additionalProperties;

    private PlanVersionResponseData(
            OffsetDateTime createdAt,
            String description,
            String environmentId,
            String icon,
            String id,
            String name,
            Optional<String> originalPlanId,
            PlanType planType,
            PlanVersionStatus status,
            OffsetDateTime updatedAt,
            long version,
            Map<String, Object> additionalProperties) {
        this.createdAt = createdAt;
        this.description = description;
        this.environmentId = environmentId;
        this.icon = icon;
        this.id = id;
        this.name = name;
        this.originalPlanId = originalPlanId;
        this.planType = planType;
        this.status = status;
        this.updatedAt = updatedAt;
        this.version = version;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("created_at")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    @JsonProperty("environment_id")
    public String getEnvironmentId() {
        return environmentId;
    }

    @JsonProperty("icon")
    public String getIcon() {
        return icon;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("original_plan_id")
    public Optional<String> getOriginalPlanId() {
        return originalPlanId;
    }

    @JsonProperty("plan_type")
    public PlanType getPlanType() {
        return planType;
    }

    @JsonProperty("status")
    public PlanVersionStatus getStatus() {
        return status;
    }

    @JsonProperty("updated_at")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonProperty("version")
    public long getVersion() {
        return version;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PlanVersionResponseData && equalTo((PlanVersionResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PlanVersionResponseData other) {
        return createdAt.equals(other.createdAt)
                && description.equals(other.description)
                && environmentId.equals(other.environmentId)
                && icon.equals(other.icon)
                && id.equals(other.id)
                && name.equals(other.name)
                && originalPlanId.equals(other.originalPlanId)
                && planType.equals(other.planType)
                && status.equals(other.status)
                && updatedAt.equals(other.updatedAt)
                && version == other.version;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.createdAt,
                this.description,
                this.environmentId,
                this.icon,
                this.id,
                this.name,
                this.originalPlanId,
                this.planType,
                this.status,
                this.updatedAt,
                this.version);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CreatedAtStage builder() {
        return new Builder();
    }

    public interface CreatedAtStage {
        DescriptionStage createdAt(@NotNull OffsetDateTime createdAt);

        Builder from(PlanVersionResponseData other);
    }

    public interface DescriptionStage {
        EnvironmentIdStage description(@NotNull String description);
    }

    public interface EnvironmentIdStage {
        IconStage environmentId(@NotNull String environmentId);
    }

    public interface IconStage {
        IdStage icon(@NotNull String icon);
    }

    public interface IdStage {
        NameStage id(@NotNull String id);
    }

    public interface NameStage {
        PlanTypeStage name(@NotNull String name);
    }

    public interface PlanTypeStage {
        StatusStage planType(@NotNull PlanType planType);
    }

    public interface StatusStage {
        UpdatedAtStage status(@NotNull PlanVersionStatus status);
    }

    public interface UpdatedAtStage {
        VersionStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface VersionStage {
        _FinalStage version(long version);
    }

    public interface _FinalStage {
        PlanVersionResponseData build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage originalPlanId(Optional<String> originalPlanId);

        _FinalStage originalPlanId(String originalPlanId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CreatedAtStage,
                    DescriptionStage,
                    EnvironmentIdStage,
                    IconStage,
                    IdStage,
                    NameStage,
                    PlanTypeStage,
                    StatusStage,
                    UpdatedAtStage,
                    VersionStage,
                    _FinalStage {
        private OffsetDateTime createdAt;

        private String description;

        private String environmentId;

        private String icon;

        private String id;

        private String name;

        private PlanType planType;

        private PlanVersionStatus status;

        private OffsetDateTime updatedAt;

        private long version;

        private Optional<String> originalPlanId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PlanVersionResponseData other) {
            createdAt(other.getCreatedAt());
            description(other.getDescription());
            environmentId(other.getEnvironmentId());
            icon(other.getIcon());
            id(other.getId());
            name(other.getName());
            originalPlanId(other.getOriginalPlanId());
            planType(other.getPlanType());
            status(other.getStatus());
            updatedAt(other.getUpdatedAt());
            version(other.getVersion());
            return this;
        }

        @java.lang.Override
        @JsonSetter("created_at")
        public DescriptionStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("description")
        public EnvironmentIdStage description(@NotNull String description) {
            this.description = Objects.requireNonNull(description, "description must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("environment_id")
        public IconStage environmentId(@NotNull String environmentId) {
            this.environmentId = Objects.requireNonNull(environmentId, "environmentId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("icon")
        public IdStage icon(@NotNull String icon) {
            this.icon = Objects.requireNonNull(icon, "icon must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public PlanTypeStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("plan_type")
        public StatusStage planType(@NotNull PlanType planType) {
            this.planType = Objects.requireNonNull(planType, "planType must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public UpdatedAtStage status(@NotNull PlanVersionStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updated_at")
        public VersionStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("version")
        public _FinalStage version(long version) {
            this.version = version;
            return this;
        }

        @java.lang.Override
        public _FinalStage originalPlanId(String originalPlanId) {
            this.originalPlanId = Optional.ofNullable(originalPlanId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "original_plan_id", nulls = Nulls.SKIP)
        public _FinalStage originalPlanId(Optional<String> originalPlanId) {
            this.originalPlanId = originalPlanId;
            return this;
        }

        @java.lang.Override
        public PlanVersionResponseData build() {
            return new PlanVersionResponseData(
                    createdAt,
                    description,
                    environmentId,
                    icon,
                    id,
                    name,
                    originalPlanId,
                    planType,
                    status,
                    updatedAt,
                    version,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
