/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RulesEngineSchemaVersion {
    public static final RulesEngineSchemaVersion V_313_FA_646 =
            new RulesEngineSchemaVersion(Value.V_313_FA_646, "v313fa646");

    public static final RulesEngineSchemaVersion PLACEHOLDER_FOR_FERN_COMPATIBILITY = new RulesEngineSchemaVersion(
            Value.PLACEHOLDER_FOR_FERN_COMPATIBILITY, "placeholder-for-fern-compatibility");

    private final Value value;

    private final String string;

    RulesEngineSchemaVersion(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof RulesEngineSchemaVersion
                        && this.string.equals(((RulesEngineSchemaVersion) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case V_313_FA_646:
                return visitor.visitV313Fa646();
            case PLACEHOLDER_FOR_FERN_COMPATIBILITY:
                return visitor.visitPlaceholderForFernCompatibility();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RulesEngineSchemaVersion valueOf(String value) {
        switch (value) {
            case "v313fa646":
                return V_313_FA_646;
            case "placeholder-for-fern-compatibility":
                return PLACEHOLDER_FOR_FERN_COMPATIBILITY;
            default:
                return new RulesEngineSchemaVersion(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        V_313_FA_646,

        PLACEHOLDER_FOR_FERN_COMPATIBILITY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitV313Fa646();

        T visitPlaceholderForFernCompatibility();

        T visitUnknown(String unknownType);
    }
}
