/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RulesengineConditionConditionType {
    public static final RulesengineConditionConditionType CRM_PRODUCT =
            new RulesengineConditionConditionType(Value.CRM_PRODUCT, "crm_product");

    public static final RulesengineConditionConditionType BASE_PLAN =
            new RulesengineConditionConditionType(Value.BASE_PLAN, "base_plan");

    public static final RulesengineConditionConditionType METRIC =
            new RulesengineConditionConditionType(Value.METRIC, "metric");

    public static final RulesengineConditionConditionType PLAN =
            new RulesengineConditionConditionType(Value.PLAN, "plan");

    public static final RulesengineConditionConditionType TRAIT =
            new RulesengineConditionConditionType(Value.TRAIT, "trait");

    public static final RulesengineConditionConditionType CREDIT =
            new RulesengineConditionConditionType(Value.CREDIT, "credit");

    public static final RulesengineConditionConditionType BILLING_PRODUCT =
            new RulesengineConditionConditionType(Value.BILLING_PRODUCT, "billing_product");

    public static final RulesengineConditionConditionType USER =
            new RulesengineConditionConditionType(Value.USER, "user");

    public static final RulesengineConditionConditionType COMPANY =
            new RulesengineConditionConditionType(Value.COMPANY, "company");

    private final Value value;

    private final String string;

    RulesengineConditionConditionType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof RulesengineConditionConditionType
                        && this.string.equals(((RulesengineConditionConditionType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CRM_PRODUCT:
                return visitor.visitCrmProduct();
            case BASE_PLAN:
                return visitor.visitBasePlan();
            case METRIC:
                return visitor.visitMetric();
            case PLAN:
                return visitor.visitPlan();
            case TRAIT:
                return visitor.visitTrait();
            case CREDIT:
                return visitor.visitCredit();
            case BILLING_PRODUCT:
                return visitor.visitBillingProduct();
            case USER:
                return visitor.visitUser();
            case COMPANY:
                return visitor.visitCompany();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RulesengineConditionConditionType valueOf(String value) {
        switch (value) {
            case "crm_product":
                return CRM_PRODUCT;
            case "base_plan":
                return BASE_PLAN;
            case "metric":
                return METRIC;
            case "plan":
                return PLAN;
            case "trait":
                return TRAIT;
            case "credit":
                return CREDIT;
            case "billing_product":
                return BILLING_PRODUCT;
            case "user":
                return USER;
            case "company":
                return COMPANY;
            default:
                return new RulesengineConditionConditionType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        BASE_PLAN,

        BILLING_PRODUCT,

        COMPANY,

        CREDIT,

        CRM_PRODUCT,

        METRIC,

        PLAN,

        TRAIT,

        USER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitBasePlan();

        T visitBillingProduct();

        T visitCompany();

        T visitCredit();

        T visitCrmProduct();

        T visitMetric();

        T visitPlan();

        T visitTrait();

        T visitUser();

        T visitUnknown(String unknownType);
    }
}
