/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RuleRuleType {
    public static final RuleRuleType GLOBAL_OVERRIDE = new RuleRuleType(Value.GLOBAL_OVERRIDE, "global_override");

    public static final RuleRuleType COMPANY_OVERRIDE = new RuleRuleType(Value.COMPANY_OVERRIDE, "company_override");

    public static final RuleRuleType COMPANY_OVERRIDE_USAGE_EXCEEDED =
            new RuleRuleType(Value.COMPANY_OVERRIDE_USAGE_EXCEEDED, "company_override_usage_exceeded");

    public static final RuleRuleType PLAN_ENTITLEMENT_USAGE_EXCEEDED =
            new RuleRuleType(Value.PLAN_ENTITLEMENT_USAGE_EXCEEDED, "plan_entitlement_usage_exceeded");

    public static final RuleRuleType STANDARD = new RuleRuleType(Value.STANDARD, "standard");

    public static final RuleRuleType DEFAULT = new RuleRuleType(Value.DEFAULT, "default");

    public static final RuleRuleType PLAN_ENTITLEMENT = new RuleRuleType(Value.PLAN_ENTITLEMENT, "plan_entitlement");

    private final Value value;

    private final String string;

    RuleRuleType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof RuleRuleType && this.string.equals(((RuleRuleType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case GLOBAL_OVERRIDE:
                return visitor.visitGlobalOverride();
            case COMPANY_OVERRIDE:
                return visitor.visitCompanyOverride();
            case COMPANY_OVERRIDE_USAGE_EXCEEDED:
                return visitor.visitCompanyOverrideUsageExceeded();
            case PLAN_ENTITLEMENT_USAGE_EXCEEDED:
                return visitor.visitPlanEntitlementUsageExceeded();
            case STANDARD:
                return visitor.visitStandard();
            case DEFAULT:
                return visitor.visitDefault();
            case PLAN_ENTITLEMENT:
                return visitor.visitPlanEntitlement();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RuleRuleType valueOf(String value) {
        switch (value) {
            case "global_override":
                return GLOBAL_OVERRIDE;
            case "company_override":
                return COMPANY_OVERRIDE;
            case "company_override_usage_exceeded":
                return COMPANY_OVERRIDE_USAGE_EXCEEDED;
            case "plan_entitlement_usage_exceeded":
                return PLAN_ENTITLEMENT_USAGE_EXCEEDED;
            case "standard":
                return STANDARD;
            case "default":
                return DEFAULT;
            case "plan_entitlement":
                return PLAN_ENTITLEMENT;
            default:
                return new RuleRuleType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DEFAULT,

        GLOBAL_OVERRIDE,

        COMPANY_OVERRIDE,

        COMPANY_OVERRIDE_USAGE_EXCEEDED,

        PLAN_ENTITLEMENT,

        PLAN_ENTITLEMENT_USAGE_EXCEEDED,

        STANDARD,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDefault();

        T visitGlobalOverride();

        T visitCompanyOverride();

        T visitCompanyOverrideUsageExceeded();

        T visitPlanEntitlement();

        T visitPlanEntitlementUsageExceeded();

        T visitStandard();

        T visitUnknown(String unknownType);
    }
}
