/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RulesengineConditionMetricPeriod {
    public static final RulesengineConditionMetricPeriod CURRENT_DAY =
            new RulesengineConditionMetricPeriod(Value.CURRENT_DAY, "current_day");

    public static final RulesengineConditionMetricPeriod ALL_TIME =
            new RulesengineConditionMetricPeriod(Value.ALL_TIME, "all_time");

    public static final RulesengineConditionMetricPeriod CURRENT_WEEK =
            new RulesengineConditionMetricPeriod(Value.CURRENT_WEEK, "current_week");

    public static final RulesengineConditionMetricPeriod CURRENT_MONTH =
            new RulesengineConditionMetricPeriod(Value.CURRENT_MONTH, "current_month");

    private final Value value;

    private final String string;

    RulesengineConditionMetricPeriod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof RulesengineConditionMetricPeriod
                        && this.string.equals(((RulesengineConditionMetricPeriod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CURRENT_DAY:
                return visitor.visitCurrentDay();
            case ALL_TIME:
                return visitor.visitAllTime();
            case CURRENT_WEEK:
                return visitor.visitCurrentWeek();
            case CURRENT_MONTH:
                return visitor.visitCurrentMonth();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RulesengineConditionMetricPeriod valueOf(String value) {
        switch (value) {
            case "current_day":
                return CURRENT_DAY;
            case "all_time":
                return ALL_TIME;
            case "current_week":
                return CURRENT_WEEK;
            case "current_month":
                return CURRENT_MONTH;
            default:
                return new RulesengineConditionMetricPeriod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ALL_TIME,

        CURRENT_DAY,

        CURRENT_MONTH,

        CURRENT_WEEK,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAllTime();

        T visitCurrentDay();

        T visitCurrentMonth();

        T visitCurrentWeek();

        T visitUnknown(String unknownType);
    }
}
