/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SubscriptionType {
    public static final SubscriptionType TRIAL = new SubscriptionType(Value.TRIAL, "trial");

    public static final SubscriptionType FREE = new SubscriptionType(Value.FREE, "free");

    public static final SubscriptionType ONE_TIME = new SubscriptionType(Value.ONE_TIME, "one_time");

    public static final SubscriptionType PAID = new SubscriptionType(Value.PAID, "paid");

    private final Value value;

    private final String string;

    SubscriptionType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SubscriptionType && this.string.equals(((SubscriptionType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TRIAL:
                return visitor.visitTrial();
            case FREE:
                return visitor.visitFree();
            case ONE_TIME:
                return visitor.visitOneTime();
            case PAID:
                return visitor.visitPaid();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SubscriptionType valueOf(String value) {
        switch (value) {
            case "trial":
                return TRIAL;
            case "free":
                return FREE;
            case "one_time":
                return ONE_TIME;
            case "paid":
                return PAID;
            default:
                return new SubscriptionType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        FREE,

        ONE_TIME,

        PAID,

        TRIAL,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitFree();

        T visitOneTime();

        T visitPaid();

        T visitTrial();

        T visitUnknown(String unknownType);
    }
}
