/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TraitDefinitionComparableType {
    public static final TraitDefinitionComparableType BOOL = new TraitDefinitionComparableType(Value.BOOL, "bool");

    public static final TraitDefinitionComparableType STRING =
            new TraitDefinitionComparableType(Value.STRING, "string");

    public static final TraitDefinitionComparableType INT = new TraitDefinitionComparableType(Value.INT, "int");

    public static final TraitDefinitionComparableType DATE = new TraitDefinitionComparableType(Value.DATE, "date");

    private final Value value;

    private final String string;

    TraitDefinitionComparableType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TraitDefinitionComparableType
                        && this.string.equals(((TraitDefinitionComparableType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case BOOL:
                return visitor.visitBool();
            case STRING:
                return visitor.visitString();
            case INT:
                return visitor.visitInt();
            case DATE:
                return visitor.visitDate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TraitDefinitionComparableType valueOf(String value) {
        switch (value) {
            case "bool":
                return BOOL;
            case "string":
                return STRING;
            case "int":
                return INT;
            case "date":
                return DATE;
            default:
                return new TraitDefinitionComparableType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        BOOL,

        DATE,

        INT,

        STRING,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitBool();

        T visitDate();

        T visitInt();

        T visitString();

        T visitUnknown(String unknownType);
    }
}
