/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TrialStatus {
    public static final TrialStatus CONVERTED = new TrialStatus(Value.CONVERTED, "converted");

    public static final TrialStatus EXPIRED = new TrialStatus(Value.EXPIRED, "expired");

    public static final TrialStatus ACTIVE = new TrialStatus(Value.ACTIVE, "active");

    private final Value value;

    private final String string;

    TrialStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof TrialStatus && this.string.equals(((TrialStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CONVERTED:
                return visitor.visitConverted();
            case EXPIRED:
                return visitor.visitExpired();
            case ACTIVE:
                return visitor.visitActive();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TrialStatus valueOf(String value) {
        switch (value) {
            case "converted":
                return CONVERTED;
            case "expired":
                return EXPIRED;
            case "active":
                return ACTIVE;
            default:
                return new TrialStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ACTIVE,

        CONVERTED,

        EXPIRED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitActive();

        T visitConverted();

        T visitExpired();

        T visitUnknown(String unknownType);
    }
}
