/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.billing.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import com.schematic.api.types.BillingProviderType;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListCompanyBillingProfilesRequest.Builder.class)
public final class ListCompanyBillingProfilesRequest {
    private final Optional<String> companyId;

    private final Optional<Boolean> isDefault;

    private final Optional<BillingProviderType> providerType;

    private final Optional<Long> limit;

    private final Optional<Long> offset;

    private final Map<String, Object> additionalProperties;

    private ListCompanyBillingProfilesRequest(
            Optional<String> companyId,
            Optional<Boolean> isDefault,
            Optional<BillingProviderType> providerType,
            Optional<Long> limit,
            Optional<Long> offset,
            Map<String, Object> additionalProperties) {
        this.companyId = companyId;
        this.isDefault = isDefault;
        this.providerType = providerType;
        this.limit = limit;
        this.offset = offset;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("company_id")
    public Optional<String> getCompanyId() {
        return companyId;
    }

    @JsonProperty("is_default")
    public Optional<Boolean> getIsDefault() {
        return isDefault;
    }

    @JsonProperty("provider_type")
    public Optional<BillingProviderType> getProviderType() {
        return providerType;
    }

    /**
     * @return Page limit (default 100)
     */
    @JsonProperty("limit")
    public Optional<Long> getLimit() {
        return limit;
    }

    /**
     * @return Page offset (default 0)
     */
    @JsonProperty("offset")
    public Optional<Long> getOffset() {
        return offset;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListCompanyBillingProfilesRequest && equalTo((ListCompanyBillingProfilesRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListCompanyBillingProfilesRequest other) {
        return companyId.equals(other.companyId)
                && isDefault.equals(other.isDefault)
                && providerType.equals(other.providerType)
                && limit.equals(other.limit)
                && offset.equals(other.offset);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.companyId, this.isDefault, this.providerType, this.limit, this.offset);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> companyId = Optional.empty();

        private Optional<Boolean> isDefault = Optional.empty();

        private Optional<BillingProviderType> providerType = Optional.empty();

        private Optional<Long> limit = Optional.empty();

        private Optional<Long> offset = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListCompanyBillingProfilesRequest other) {
            companyId(other.getCompanyId());
            isDefault(other.getIsDefault());
            providerType(other.getProviderType());
            limit(other.getLimit());
            offset(other.getOffset());
            return this;
        }

        @JsonSetter(value = "company_id", nulls = Nulls.SKIP)
        public Builder companyId(Optional<String> companyId) {
            this.companyId = companyId;
            return this;
        }

        public Builder companyId(String companyId) {
            this.companyId = Optional.ofNullable(companyId);
            return this;
        }

        @JsonSetter(value = "is_default", nulls = Nulls.SKIP)
        public Builder isDefault(Optional<Boolean> isDefault) {
            this.isDefault = isDefault;
            return this;
        }

        public Builder isDefault(Boolean isDefault) {
            this.isDefault = Optional.ofNullable(isDefault);
            return this;
        }

        @JsonSetter(value = "provider_type", nulls = Nulls.SKIP)
        public Builder providerType(Optional<BillingProviderType> providerType) {
            this.providerType = providerType;
            return this;
        }

        public Builder providerType(BillingProviderType providerType) {
            this.providerType = Optional.ofNullable(providerType);
            return this;
        }

        /**
         * <p>Page limit (default 100)</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Long> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Long limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Page offset (default 0)</p>
         */
        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public Builder offset(Optional<Long> offset) {
            this.offset = offset;
            return this;
        }

        public Builder offset(Long offset) {
            this.offset = Optional.ofNullable(offset);
            return this;
        }

        public ListCompanyBillingProfilesRequest build() {
            return new ListCompanyBillingProfilesRequest(
                    companyId, isDefault, providerType, limit, offset, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
