/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.planmigrations;

import com.schematic.api.core.ClientOptions;
import com.schematic.api.core.RequestOptions;
import com.schematic.api.resources.planmigrations.requests.CountCompanyMigrationsRequest;
import com.schematic.api.resources.planmigrations.requests.CountMigrationsRequest;
import com.schematic.api.resources.planmigrations.requests.CreateMigrationInput;
import com.schematic.api.resources.planmigrations.requests.ListCompanyMigrationsRequest;
import com.schematic.api.resources.planmigrations.requests.ListMigrationsRequest;
import com.schematic.api.resources.planmigrations.requests.RetryMigrationRequestBody;
import com.schematic.api.resources.planmigrations.types.CountCompanyMigrationsResponse;
import com.schematic.api.resources.planmigrations.types.CountMigrationsResponse;
import com.schematic.api.resources.planmigrations.types.CreateMigrationResponse;
import com.schematic.api.resources.planmigrations.types.GetMigrationResponse;
import com.schematic.api.resources.planmigrations.types.ListCompanyMigrationsResponse;
import com.schematic.api.resources.planmigrations.types.ListMigrationsResponse;
import com.schematic.api.resources.planmigrations.types.RetryCompanyMigrationResponse;
import com.schematic.api.resources.planmigrations.types.RetryMigrationResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncPlanmigrationsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawPlanmigrationsClient rawClient;

    public AsyncPlanmigrationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawPlanmigrationsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawPlanmigrationsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<ListCompanyMigrationsResponse> listCompanyMigrations() {
        return this.rawClient.listCompanyMigrations().thenApply(response -> response.body());
    }

    public CompletableFuture<ListCompanyMigrationsResponse> listCompanyMigrations(RequestOptions requestOptions) {
        return this.rawClient.listCompanyMigrations(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<ListCompanyMigrationsResponse> listCompanyMigrations(
            ListCompanyMigrationsRequest request) {
        return this.rawClient.listCompanyMigrations(request).thenApply(response -> response.body());
    }

    public CompletableFuture<ListCompanyMigrationsResponse> listCompanyMigrations(
            ListCompanyMigrationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listCompanyMigrations(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<RetryCompanyMigrationResponse> retryCompanyMigration(
            String planVersionCompanyMigrationId) {
        return this.rawClient
                .retryCompanyMigration(planVersionCompanyMigrationId)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<RetryCompanyMigrationResponse> retryCompanyMigration(
            String planVersionCompanyMigrationId, RequestOptions requestOptions) {
        return this.rawClient
                .retryCompanyMigration(planVersionCompanyMigrationId, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<CountCompanyMigrationsResponse> countCompanyMigrations() {
        return this.rawClient.countCompanyMigrations().thenApply(response -> response.body());
    }

    public CompletableFuture<CountCompanyMigrationsResponse> countCompanyMigrations(RequestOptions requestOptions) {
        return this.rawClient.countCompanyMigrations(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<CountCompanyMigrationsResponse> countCompanyMigrations(
            CountCompanyMigrationsRequest request) {
        return this.rawClient.countCompanyMigrations(request).thenApply(response -> response.body());
    }

    public CompletableFuture<CountCompanyMigrationsResponse> countCompanyMigrations(
            CountCompanyMigrationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.countCompanyMigrations(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<ListMigrationsResponse> listMigrations() {
        return this.rawClient.listMigrations().thenApply(response -> response.body());
    }

    public CompletableFuture<ListMigrationsResponse> listMigrations(RequestOptions requestOptions) {
        return this.rawClient.listMigrations(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<ListMigrationsResponse> listMigrations(ListMigrationsRequest request) {
        return this.rawClient.listMigrations(request).thenApply(response -> response.body());
    }

    public CompletableFuture<ListMigrationsResponse> listMigrations(
            ListMigrationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listMigrations(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<CreateMigrationResponse> createMigration(CreateMigrationInput request) {
        return this.rawClient.createMigration(request).thenApply(response -> response.body());
    }

    public CompletableFuture<CreateMigrationResponse> createMigration(
            CreateMigrationInput request, RequestOptions requestOptions) {
        return this.rawClient.createMigration(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetMigrationResponse> getMigration(String planVersionMigrationId) {
        return this.rawClient.getMigration(planVersionMigrationId).thenApply(response -> response.body());
    }

    public CompletableFuture<GetMigrationResponse> getMigration(
            String planVersionMigrationId, RequestOptions requestOptions) {
        return this.rawClient
                .getMigration(planVersionMigrationId, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<RetryMigrationResponse> retryMigration(
            String planVersionMigrationId, RetryMigrationRequestBody request) {
        return this.rawClient.retryMigration(planVersionMigrationId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<RetryMigrationResponse> retryMigration(
            String planVersionMigrationId, RetryMigrationRequestBody request, RequestOptions requestOptions) {
        return this.rawClient
                .retryMigration(planVersionMigrationId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<CountMigrationsResponse> countMigrations() {
        return this.rawClient.countMigrations().thenApply(response -> response.body());
    }

    public CompletableFuture<CountMigrationsResponse> countMigrations(RequestOptions requestOptions) {
        return this.rawClient.countMigrations(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<CountMigrationsResponse> countMigrations(CountMigrationsRequest request) {
        return this.rawClient.countMigrations(request).thenApply(response -> response.body());
    }

    public CompletableFuture<CountMigrationsResponse> countMigrations(
            CountMigrationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.countMigrations(request, requestOptions).thenApply(response -> response.body());
    }
}
