/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.plangroups.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetPlanGroupParams.Builder.class)
public final class GetPlanGroupParams {
    private final Optional<Boolean> includeCompanyCounts;

    private final Map<String, Object> additionalProperties;

    private GetPlanGroupParams(Optional<Boolean> includeCompanyCounts, Map<String, Object> additionalProperties) {
        this.includeCompanyCounts = includeCompanyCounts;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("include_company_counts")
    public Optional<Boolean> getIncludeCompanyCounts() {
        return includeCompanyCounts;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetPlanGroupParams && equalTo((GetPlanGroupParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetPlanGroupParams other) {
        return includeCompanyCounts.equals(other.includeCompanyCounts);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.includeCompanyCounts);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> includeCompanyCounts = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetPlanGroupParams other) {
            includeCompanyCounts(other.getIncludeCompanyCounts());
            return this;
        }

        @JsonSetter(value = "include_company_counts", nulls = Nulls.SKIP)
        public Builder includeCompanyCounts(Optional<Boolean> includeCompanyCounts) {
            this.includeCompanyCounts = includeCompanyCounts;
            return this;
        }

        public Builder includeCompanyCounts(Boolean includeCompanyCounts) {
            this.includeCompanyCounts = Optional.ofNullable(includeCompanyCounts);
            return this;
        }

        public GetPlanGroupParams build() {
            return new GetPlanGroupParams(includeCompanyCounts, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
