/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.entitlements.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetUserUsageByCompanyParams.Builder.class)
public final class GetUserUsageByCompanyParams {
    private final Optional<String> companyId;

    private final Optional<OffsetDateTime> endTime;

    private final Optional<String> featureId;

    private final Optional<OffsetDateTime> startTime;

    private final Map<String, Object> additionalProperties;

    private GetUserUsageByCompanyParams(
            Optional<String> companyId,
            Optional<OffsetDateTime> endTime,
            Optional<String> featureId,
            Optional<OffsetDateTime> startTime,
            Map<String, Object> additionalProperties) {
        this.companyId = companyId;
        this.endTime = endTime;
        this.featureId = featureId;
        this.startTime = startTime;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Company to break usage down for
     */
    @JsonProperty("company_id")
    public Optional<String> getCompanyId() {
        return companyId;
    }

    /**
     * @return End of the usage window (exclusive); defaults to now
     */
    @JsonProperty("end_time")
    public Optional<OffsetDateTime> getEndTime() {
        return endTime;
    }

    /**
     * @return Restrict to a single event-based feature
     */
    @JsonProperty("feature_id")
    public Optional<String> getFeatureId() {
        return featureId;
    }

    /**
     * @return Start of the usage window; defaults to 30 days before the end
     */
    @JsonProperty("start_time")
    public Optional<OffsetDateTime> getStartTime() {
        return startTime;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetUserUsageByCompanyParams && equalTo((GetUserUsageByCompanyParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetUserUsageByCompanyParams other) {
        return companyId.equals(other.companyId)
                && endTime.equals(other.endTime)
                && featureId.equals(other.featureId)
                && startTime.equals(other.startTime);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.companyId, this.endTime, this.featureId, this.startTime);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> companyId = Optional.empty();

        private Optional<OffsetDateTime> endTime = Optional.empty();

        private Optional<String> featureId = Optional.empty();

        private Optional<OffsetDateTime> startTime = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetUserUsageByCompanyParams other) {
            companyId(other.getCompanyId());
            endTime(other.getEndTime());
            featureId(other.getFeatureId());
            startTime(other.getStartTime());
            return this;
        }

        /**
         * <p>Company to break usage down for</p>
         */
        @JsonSetter(value = "company_id", nulls = Nulls.SKIP)
        public Builder companyId(Optional<String> companyId) {
            this.companyId = companyId;
            return this;
        }

        public Builder companyId(String companyId) {
            this.companyId = Optional.ofNullable(companyId);
            return this;
        }

        /**
         * <p>End of the usage window (exclusive); defaults to now</p>
         */
        @JsonSetter(value = "end_time", nulls = Nulls.SKIP)
        public Builder endTime(Optional<OffsetDateTime> endTime) {
            this.endTime = endTime;
            return this;
        }

        public Builder endTime(OffsetDateTime endTime) {
            this.endTime = Optional.ofNullable(endTime);
            return this;
        }

        /**
         * <p>Restrict to a single event-based feature</p>
         */
        @JsonSetter(value = "feature_id", nulls = Nulls.SKIP)
        public Builder featureId(Optional<String> featureId) {
            this.featureId = featureId;
            return this;
        }

        public Builder featureId(String featureId) {
            this.featureId = Optional.ofNullable(featureId);
            return this;
        }

        /**
         * <p>Start of the usage window; defaults to 30 days before the end</p>
         */
        @JsonSetter(value = "start_time", nulls = Nulls.SKIP)
        public Builder startTime(Optional<OffsetDateTime> startTime) {
            this.startTime = startTime;
            return this;
        }

        public Builder startTime(OffsetDateTime startTime) {
            this.startTime = Optional.ofNullable(startTime);
            return this;
        }

        public GetUserUsageByCompanyParams build() {
            return new GetUserUsageByCompanyParams(companyId, endTime, featureId, startTime, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
