/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.planmigrations.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import com.schematic.api.types.PlanVersionMigrationStatus;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListMigrationsRequest.Builder.class)
public final class ListMigrationsRequest {
    private final Optional<String> planVersionId;

    private final Optional<PlanVersionMigrationStatus> status;

    private final Optional<Long> limit;

    private final Optional<Long> offset;

    private final Map<String, Object> additionalProperties;

    private ListMigrationsRequest(
            Optional<String> planVersionId,
            Optional<PlanVersionMigrationStatus> status,
            Optional<Long> limit,
            Optional<Long> offset,
            Map<String, Object> additionalProperties) {
        this.planVersionId = planVersionId;
        this.status = status;
        this.limit = limit;
        this.offset = offset;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("plan_version_id")
    public Optional<String> getPlanVersionId() {
        return planVersionId;
    }

    @JsonProperty("status")
    public Optional<PlanVersionMigrationStatus> getStatus() {
        return status;
    }

    /**
     * @return Page limit (default 100)
     */
    @JsonProperty("limit")
    public Optional<Long> getLimit() {
        return limit;
    }

    /**
     * @return Page offset (default 0)
     */
    @JsonProperty("offset")
    public Optional<Long> getOffset() {
        return offset;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListMigrationsRequest && equalTo((ListMigrationsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListMigrationsRequest other) {
        return planVersionId.equals(other.planVersionId)
                && status.equals(other.status)
                && limit.equals(other.limit)
                && offset.equals(other.offset);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.planVersionId, this.status, this.limit, this.offset);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> planVersionId = Optional.empty();

        private Optional<PlanVersionMigrationStatus> status = Optional.empty();

        private Optional<Long> limit = Optional.empty();

        private Optional<Long> offset = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListMigrationsRequest other) {
            planVersionId(other.getPlanVersionId());
            status(other.getStatus());
            limit(other.getLimit());
            offset(other.getOffset());
            return this;
        }

        @JsonSetter(value = "plan_version_id", nulls = Nulls.SKIP)
        public Builder planVersionId(Optional<String> planVersionId) {
            this.planVersionId = planVersionId;
            return this;
        }

        public Builder planVersionId(String planVersionId) {
            this.planVersionId = Optional.ofNullable(planVersionId);
            return this;
        }

        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<PlanVersionMigrationStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(PlanVersionMigrationStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Page limit (default 100)</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Long> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Long limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Page offset (default 0)</p>
         */
        @JsonSetter(value = "offset", nulls = Nulls.SKIP)
        public Builder offset(Optional<Long> offset) {
            this.offset = offset;
            return this;
        }

        public Builder offset(Long offset) {
            this.offset = Optional.ofNullable(offset);
            return this;
        }

        public ListMigrationsRequest build() {
            return new ListMigrationsRequest(planVersionId, status, limit, offset, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
