/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.schematic.api.resources.integrationsapi.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.schematic.api.core.ObjectMappers;
import com.schematic.api.types.IntegrationsListResponseData;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListIntegrationsResponse.Builder.class)
public final class ListIntegrationsResponse {
    private final List<IntegrationsListResponseData> data;

    private final ListIntegrationsParams params;

    private final Map<String, Object> additionalProperties;

    private ListIntegrationsResponse(
            List<IntegrationsListResponseData> data,
            ListIntegrationsParams params,
            Map<String, Object> additionalProperties) {
        this.data = data;
        this.params = params;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("data")
    public List<IntegrationsListResponseData> getData() {
        return data;
    }

    /**
     * @return Input parameters
     */
    @JsonProperty("params")
    public ListIntegrationsParams getParams() {
        return params;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListIntegrationsResponse && equalTo((ListIntegrationsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListIntegrationsResponse other) {
        return data.equals(other.data) && params.equals(other.params);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.params);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ParamsStage builder() {
        return new Builder();
    }

    public interface ParamsStage {
        /**
         * <p>Input parameters</p>
         */
        _FinalStage params(@NotNull ListIntegrationsParams params);

        Builder from(ListIntegrationsResponse other);
    }

    public interface _FinalStage {
        ListIntegrationsResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage data(List<IntegrationsListResponseData> data);

        _FinalStage addData(IntegrationsListResponseData data);

        _FinalStage addAllData(List<IntegrationsListResponseData> data);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ParamsStage, _FinalStage {
        private ListIntegrationsParams params;

        private List<IntegrationsListResponseData> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListIntegrationsResponse other) {
            data(other.getData());
            params(other.getParams());
            return this;
        }

        /**
         * <p>Input parameters</p>
         * <p>Input parameters</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("params")
        public _FinalStage params(@NotNull ListIntegrationsParams params) {
            this.params = Objects.requireNonNull(params, "params must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllData(List<IntegrationsListResponseData> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addData(IntegrationsListResponseData data) {
            this.data.add(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(List<IntegrationsListResponseData> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public ListIntegrationsResponse build() {
            return new ListIntegrationsResponse(data, params, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
